# Generated by Django 4.1 on 2022-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('CollegeName', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
    ]
