# Generated by Django 4.1 on 2022-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='RollNo',
            field=models.IntegerField(null=True),
        ),
    ]
